# Setup
title:               Brian Lee's Blog
# tagline:             'A Jekyll theme'
description:         ''
url:                 https://www.briansmlee.com
# baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Brian Lee
  url:               https://twitter.com/brianleesm
  github_username:   bransmlee
  email:             '[github username] [AT] gmail'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

##### My vars #####
markdown: kramdown
highlighter: rouge

collections:
  esl_posts:
    output: true
    sort_by: section_title

